#!/bin/bash
# 自動生成的清理腳本 - 請仔細檢查後再執行
# 此腳本會刪除未使用的檔案

set -e

echo '⚠️  警告：此腳本將刪除以下檔案...'
echo '請確認後再執行！'

# content_images
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/about/04.about-photographer-4-dm.jpg.JPG'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/blog.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/family/family-9.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/Support_Image_Main.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/korean-id/korean-id.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/medical/medical-6.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/medical/medical-7.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/medical/medical-8.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/medical/medical-9.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/pet/pet-6.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/pet/pet-7.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/pet/pet-8.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/pet/pet-9.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/profile-1.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/profile-2.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/workshop/Whisper_Blessing.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/workshop/service-workshop-1.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/workshop/service-workshop-2.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/home/hero/Hero_Images_16x9.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/price-list/Group_Example_3.jpg.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/price-list/Group_Example_4.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/price-list/Group_Example_4.jpg.jpg.jpg'

# other
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/ACCESSIBILITY_COLOR_REPORT.json'

# portfolio_images
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-10.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-11.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-12.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-13.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-14.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-15.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-16.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-17.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-18.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-19.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-20.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-21.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-22.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-23.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-24.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-25.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-26.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-27.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-28.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-29.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-3.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-30.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-31.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-32.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-33.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-34.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-35.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-36.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-37.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-38.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-39.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-4.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-40.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-41.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-42.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-43.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-44.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-45.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-46.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-47.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-48.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-49.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-5.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-6.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-7.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-8.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-9.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-1.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-10.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-11.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-12.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-13.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-14.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-15.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-16.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-17.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-18.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-19.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-2.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-20.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-21.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-22.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-23.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-24.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-25.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-26.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-27.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-28.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-29.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-3.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-4.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-5.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-6.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-7.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-8.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-9.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-10.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-11.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-12.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-13.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-14.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-15.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-16.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-5.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-6.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-7.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-8.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-9.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/campaign-portrait/campaign-portrait-5.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/chill-vibe/chill-vibe-1.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/chill-vibe/chill-vibe-2.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/chill-vibe/chill-vibe-3.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/friends-portrait/GGC09394.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/friends-portrait/Untitled (48).jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/legacy-portrait/legacy-1.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/legacy-portrait/legacy-2.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/pet/musician-portrait-1.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/pet/musician-portrait-2.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/pet/musician-portrait-3.jpg'

# template_files
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/ACCESSIBILITY_COLOR_REPORT.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/ACCESSIBILITY_FIXES_SUMMARY.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/BUTTON_AUDIT_REPORT.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/BUTTON_SYSTEM_GUIDE.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/COLOR_AUDIT_REPORT.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/COMPLETE_EXTENSION_REPORT.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/COMPONENT_LIBRARY_SUMMARY.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/DEPRECATED_TOKENS_AND_VARIANTS_REPORT.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/DEPRECATED_TOKENS_CLEANUP_SUMMARY.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/DESIGN_AUDIT_REPORT.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/DESIGN_SYSTEM_AUDIT_REPORT.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/EXTENSION_SUMMARY.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/FINAL_COMPLETE_REPORT.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/FINAL_EXTENSION_REPORT.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/HEADER_DESIGN_PLAN.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/LONG_TERM_TASKS_SUMMARY.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/MANUAL_TEST_CHECKLIST.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/MIGRATION_COMPLETE_SUMMARY.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/MIGRATION_DEMO.njk'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/MIGRATION_EXAMPLE.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/MIGRATION_PHASE2_SUMMARY.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/MIGRATION_PHASE3_COMPLETE.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/MIGRATION_PROGRESS.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/MIGRATION_START_SUMMARY.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/MIGRATION_SUGGESTIONS.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/MIGRATION_TEST_REPORT.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/TESTING_SUMMARY.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/TOKEN_MIGRATION_SUMMARY.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/TOKEN_SYSTEM_MIGRATION_PLAN.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/UNDEFINED_COLORS_REPORT.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/VARIANT_STANDARDIZATION_SUMMARY.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/VARIANT_SYSTEM_IMPLEMENTATION.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/VISUAL_TEST_REPORT.md'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/guide/identity-test.njk'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/test-homepage-1.html'

# ui_images
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/ui/logo2.png'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/ui/logo3.jpeg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/ui/logo3.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/ui/paper-texture.jpg'

echo '✅ 清理完成'
