#!/bin/bash
# 自動生成的清理腳本 - 請仔細檢查後再執行
# 此腳本會刪除未使用的檔案

set -e

echo '⚠️  警告：此腳本將刪除以下檔案...'
echo '請確認後再執行！'

# portfolio_images
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-10.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-11.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-12.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-13.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-14.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-15.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-16.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-17.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-18.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-19.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-20.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-21.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-22.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-23.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-24.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-25.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-26.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-27.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-28.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-29.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-3.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-30.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-31.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-32.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-33.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-34.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-35.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-36.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-37.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-38.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-39.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-4.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-40.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-41.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-42.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-43.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-44.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-45.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-46.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-47.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-48.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-49.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-5.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-6.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-7.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-8.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/couples/portfolio-wall/couples-9.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-1.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-10.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-11.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-12.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-13.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-14.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-15.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-16.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-17.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-18.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-19.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-2.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-20.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-21.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-22.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-23.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-24.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-25.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-26.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-27.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-28.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-29.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-3.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-4.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-5.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-6.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-7.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-8.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/graduation/portfolio-wall/graduation-9.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-10.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-11.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-12.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-13.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-14.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-15.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-16.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-5.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-6.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-7.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-8.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/content/blog/profile/portfolio-wall/profile-9.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/campaign-portrait/campaign-portrait-5.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/chill-vibe/chill-vibe-1.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/chill-vibe/chill-vibe-2.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/chill-vibe/chill-vibe-3.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/friends-portrait/GGC09394.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/friends-portrait/Untitled (48).jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/legacy-portrait/legacy-1.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/legacy-portrait/legacy-2.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/pet/musician-portrait-1.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/pet/musician-portrait-2.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/portfolio/pet/musician-portrait-3.jpg'

# ui_images
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/ui/logo2.png'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/ui/logo3.jpeg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/ui/logo3.jpg'
rm -v '/Users/jackm4/Documents/GitHub/goldenyearsphoto/src/assets/images/ui/paper-texture.jpg'

echo '✅ 清理完成'
